#!/bin/bash

bluetooth_device_connected=0
device_name="null"

# Check if any bluetooth device is connected
while read -r uuid; do
    if  bluetoothctl info $uuid | grep -q "Connected: yes"; then
        device_name=$(bluetoothctl info $uuid | grep "Name" | awk '{print $2}')
        bluetooth_device_connected=1
        break
    fi
done < <(bluetoothctl devices | awk '{print $2}')

if [ "$bluetooth_device_connected" -eq 0 ] ; then
    icon="󰂲"
    text=""
    col="#38384D"
    eww update bt_toggle=false

else
    icon="󰂯"
    text="${device_name}"
    col="#b7bdf8"
    eww update bt_toggle=true
fi

if [[ "$1" == "--color" ]]; then
    echo $col	
elif [[ "$1" == "--name" ]]; then
	echo $text
elif [[ "$1" == "--icon" ]]; then
	echo $icon
fi

