#!/bin/bash

status=$(nmcli g | grep -oE "disconnected")
essid="$(nmcli c | grep wlan0 | awk '{print ($1)}')"

if [ $status ] ; then
    icon="󰤯"
    text=""
    col="#38384D"
    eww update wifi_toggle=false

else
    icon="󰖩"
    text="${essid}"
    col="#a6da95"
    eww update wifi_toggle=true
fi

if [[ "$1" == "--color" ]]; then
    echo $col	
elif [[ "$1" == "--name" ]]; then
	echo $text
elif [[ "$1" == "--icon" ]]; then
	echo $icon
fi

