#!/bin/bash

status=$(nmcli g | grep -oE "disconnected")
if [ -d "/proc/acpi/button/lid" ]; then
    essid="$(nmcli c | grep wlan0 | awk '{print ($1)}')"
else
    essid="$(nmcli c | grep wlp4s0 | awk '{print ($1)}')"
fi

if [ $status ] ; then
    icon="󰖪"
    text=""
    col="#38384D"
    eww update wifi_toggle=false

else
    icon="󰖩"
    text="${essid}"
    col="#f5c2e7"
    eww update wifi_toggle=true
fi

if [[ "$1" == "--color" ]]; then
    echo $col	
elif [[ "$1" == "--name" ]]; then
	echo $text
elif [[ "$1" == "--icon" ]]; then
	echo $icon
fi
