notify = true
repeat = "playlist"
shuffle = true
volnorm = true
[keybindings]
    playpause = "XF86AudioPlay"
    previous = "XF86AudioPrev"
    next = "XF86AudioNext"
[theme]
    primary = "light white"
    secondary = "light black"
    title = "green"
    playing = "#98971a"
    # playing_selected = "#98971a"
    playing_bg = "black"
    highlight = "#98971a"
    highlight_bg = "#1d2021"
    error = "light white"
    error_bg = "red"
    statusbar = "#98971a"
    statusbar_progress = "#98971a"
    # statusbar_bg = "#98971a"
    cmdline = "light white"
    cmdline_bg = "black"
    search_match = "light red"

