set autocd
set globdots
set nobeep
set nomatch
set menucomplete
set extendedglob
set interactivecomments
set appendhistory
set histignorespace
set histignoredups
set banghist
set extendedhistory
set histexpiredupsfirst
set histignoredups
set histignorealldups
set histfindnodups
set histignorespace
set histsavenodups
set histreduceblanks
set histverify
