#!/bin/bash

set_title() {
    if [[ ${1:0:12} == "activewindow" && ${1:0:14} != "activewindowv2" ]]; then #set focused workspace
        string=${1:14}
        title="${string/,*/}"
    fi
}

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
set_title "$event"
echo $title
done
