#!/bin/bash

get_wifi() {
    nmcli -t -f NAME c | head -n 1
}

return_wifi() {
    if [[ $6 == *Not* ]]; then
        eww update wifi_state=false
    else
        eww update wifi_state=true
        get_wifi
    fi
}

# initial state
if [[ $(iwgetid) ]]; then
    eww update wifi_state=true
    get_wifi
fi

iwevent | while read -r event; do
# filter to access point changes
if [[ $event == *New* ]]; then
    return_wifi $event
fi
done
