#!/bin/bash

mkdir -p /tmp/eww
file=/tmp/eww/bluetooth

get_bt() {
    bluetoothctl info $uuid | grep "Name" | awk '{print $2}' > $file
}

return_bt() {
    if [[ $(echo $@ | grep -o 'yes') ]]; then
        eww update bt_state=true
        get_bt
    else
        eww update bt_state=false
    fi
}

# initial state
if [[ $(get_bt) ]]; then
    eww update bt_state=true
    get_bt
fi

bluetoothctl | while read -r event; do
# filter to access point changes
    if [[ $event == *Connected* ]]; then
        return_bt $event
    fi
done
