#!/bin/bash

mkdir -p /tmp/eww
file=/tmp/eww/bluetooth

[ -z $file ] && touch $file

get_bt() {
    bluetoothctl info | grep "Name" | awk '{print $2}' > $file
}

return_bt() {
    if echo "$@" | grep -qo 'yes'; then
        eww update bt_state=true
        get_bt
    else
        eww update bt_state=false
    fi
}

# initial state
if [[ $(bluetoothctl info | grep "Name" | awk '{print $2}') ]]; then
    eww update bt_state=true
    get_bt
else
    eww update bt_state=false
fi

bluetoothctl | while read -r event; do
# filter to access point changes
    if [[ $event == *Connected* ]]; then
        return_bt "$event"
    fi
done
