#!/bin/bash

status=$(nmcli g | grep -oE "disconnected")
if [ -d "/proc/acpi/button/lid" ]; then
    interface="wlan0"
else
    interface="wlp3s0"
fi

essid=$(nmcli -t -f NAME c | head -n 1)

if [ $status ] ; then
    icon="󰖪"
    text=""
    col="#38384D"
    eww update wifi_toggle=false

else
    icon="󰖩"
    text=$essid
    col="#ffffff"
    eww update wifi_toggle=true
fi

if [[ "$1" == "--color" ]]; then
    echo $col	
elif [[ "$1" == "--name" ]]; then
	echo $text
elif [[ "$1" == "--icon" ]]; then
	echo $icon
fi
